### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by dragerlive** [ohMatty/CSGOShop#11]
I have this problem :Parse error: syntax error, unexpected '[' in /home/u326474077/public_html/libs/CSGOShop.class.php on line 33

**Comment by dragerlive** [comment]
CSGOShop.class.php not touch

**Comment by jamie-0-1** [comment]
You need PHP 5.4 or newer

**Comment by dragerlive** [comment]
Jamie96, I made a PHP 5.4, but after that the error changed 
Fatal error: Call to undefined function Imgur\Exception() in /home/u326474077/public_html/libs/imgur-php-wrapper/Imgur.php on line 60

**Comment by jamie-0-1** [comment]
https://github.com/ohMatty/CSGOShop/blob/master/config/app.php

Set the imgurId and appSecret to your api details

**Comment by dragerlive** [comment]
Jamie96, Where can I get a imgurId and appSecret

**Comment by dragerlive** [comment]
Jamie96, I get a imgurID and ClientSecret (appsecret) from this site https://imgur.com.
After I put everything in 
'imgur' => [
'appId' => 'My ClientID',
'appSecret' => 'ClientSecret',

'steam' => [
'apiKey' => My apiKey (steam)',
'maxInventory' => 1050

and nothing else touching (everything else is standard, as here https://github.com/ohMatty/CSGOShop/blob/master/config/app.php)
Now I have another error:
Fatal error: Uncaught exception 'ActiveRecord\ConfigException' with message 'Connections must be an array' in /home/u326474077/public_html/libs/php-activerecord/lib/Config.php:128 Stack trace: #0 /home/u326474077/public_html/libs/CSGOShop.class.php(124): ActiveRecord\Config->set_connections(true) #1 /home/u326474077/public_html/libs/CSGOShop.class.php(107): CSGOShop->setupActiveRecord() #2 /home/u326474077/public_html/libs/CSGOShop.class.php(23): CSGOShop->initClasses() #3 /home/u326474077/public_html/index.php(3): CSGOShop->__construct(true) #4 {main} thrown in /home/u326474077/public_html/libs/php-activerecord/lib/Config.php on line 128

**Comment by dragerlive** [comment]
Jamie96, Pls help

**Comment by ElPresidentePro** [comment]
What system do you use?

**Comment by ElPresidentePro** [comment]
I use xampp windows using the program and it works well

**Comment by ElPresidentePro** [comment]
Jaime a question, if you do not load the inventory and do not logs on is that this bug or for reasons Profile

**Comment by dragerlive** [comment]
I use win 7 and I don't use programms, I use hosting site hostinger.com

**Comment by ElPresidentePro** [comment]
ok hostinger you pay or free plan?

**Comment by dragerlive** [comment]
Free plan

**Comment by dragerlive** [comment]
I can download XAMPP, add me in steam аnd if not hard to tell how you did site :)
http://steamcommunity.com/id/vladlem
